### ISSUE TITLE
Nápad na zlepšenie

### ISSUE THREAD

**Issue by Klingacik** [AppsLab-2/music-maker#1]
userRepository.findByname(name) by som zbytočne nevolal 2-krát, stačí raz.

https://github.com/AppsLab-2/music-maker/blob/b9d06dbc500dbaed3f9305bb66282bec72f3836a/backend/src/main/java/com/appslab/musicmaker/MyUserDetailsService.java#L16-L22

**Comment by simonheglasik** [comment]
Opravene
https://github.com/AppsLab-2/music-maker/blob/239348fd67fa8893c897ef061bfe23d101bd9bec/backend/src/main/java/com/appslab/musicmaker/MyUserDetailsService.java#L18-L23
