### ISSUE TITLE
FE - globalne konstanty

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/music-maker#6]
String 'http://localhost:8080...' pouzivate pravdepodobne na viacerych miestach. Dobrym zvykom je mat subor s globalnymi static konstantami, kde si ulozim tento retazec a potom uz len pouzivam a pridam zvysok stringu. Vyhodne to moze byt aj vtedy, keby to chcete nasadit niekde na server a zrazu uz nebudete mat localhost:8080, no a takto to budete musiet zmenit na vela miestach.

https://github.com/AppsLab-2/music-maker/blob/ca4302fca05fd58a16a95ff10d648ba2c89215c7/frontend/src/app/pattern.service.ts#L34

**Comment by vysnezil** [comment]
fixed
https://github.com/AppsLab-2/music-maker/blob/111951d30765fb6624299941b98321ca07bc88ea/frontend/src/app/pattern.service.ts#L10
