### ISSUE TITLE
FE - poradie premennych, funkcii

### ISSUE THREAD

**Issue by katarinaHrab** [AppsLab-2/music-maker#9]
Globalne premenne (pre danu komponentu) sa pisu vsetky pokope hore pred konstruktor a az potom idu funkcie

https://github.com/AppsLab-2/music-maker/blob/ca4302fca05fd58a16a95ff10d648ba2c89215c7/frontend/src/app/song-editor/song-editor.component.ts#L40

**Comment by vysnezil** [comment]
fixed
https://github.com/AppsLab-2/music-maker/blob/111951d30765fb6624299941b98321ca07bc88ea/frontend/src/app/song-editor/song-editor.component.ts#L27
